[package]
name = "lst_optimizer_client"
version = "0.1.0"
edition = "2021"

[dependencies]
lst_optimizer_std = { path = "../lst-optimizer-std" }
controller_lib = { path = "../controller-lib" }
rust_decimal = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
solana-client = { workspace = true }
reqwest = { version = "^0.12", features = ["json"] }
ta = "0.5.0"
