[package]
name = "controller_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }

borsh = "1.5.5"
solana-client = "2.2.1"
solana-sdk = "2.2.1"
solana-program = ">=1"
solana-transaction-status = "2.2.1"
solana-readonly-account = { version = "^1.1", features = ["solana-sdk"] }
data-encoding = "2.8.0"
spl-token = ">=0.1.0"
spl-token-2022 = ">=0.1.0"
# link to https://github.com/moose-labs/S
s-controller-lib = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
s_controller_interface = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
sol_value_calculator_interface = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
generic_pool_calculator_interface = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
# calculator
lido-calculator-lib = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
marinade-calculator-lib = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
spl-calculator-lib = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
wsol-calculator-lib = { git = "https://github.com/moose-labs/S.git", branch = "custom_address" }
# helper
sanctum-token-ratio = { git = "https://github.com/igneous-labs/sanctum-solana-utils.git", features = [
    "borsh",
], branch = "f6c40a0-loose-deps" }
